# -*- coding: utf-8 -*-
"""atividade_estrutura_dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/thiagosilvabarbosa/bce162187549c1349c4121549e1f10bd/atividade_estrutura_dados.ipynb
"""

numeros = [1,1,2,1,5,4]
contador = 0
for numero in numeros:
  if numero == 1:
    contador += 1
print(contador)

numeros = [7,7,8,7,7]
somanumeros = sum(numeros)/len(numeros)
print(somanumeros)

numeros = [2,5,50,9]
maior = max(numeros)
menor = min(numeros)
print(f"maior numero = {maior}\nmenor numero = {menor}")

numeros = [1,2,3,4,5,6]
pares = []
for numero in numeros:
  if numero % 2 == 0:
    pares.append(numero)

print(pares)

lista1 = input("insira numeros da lista 1: ").split()
lista2 = input("insira numeros da lista 2: ").split()
for i in range (len(lista1)):
  lista1[i] = int(lista1[i])

for i in range (len(lista2)):
  lista2[i] = int(lista2[i])


lista3 = lista1 + lista2
lista3.sort()
print(lista3)